version: "3.9"

services:

  db:
    image: postgres:15
    container_name: wearit_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: wearit_backend
    depends_on:
      - db
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/inventory
    volumes:
      - ./backend:/app

  frontend:
    build: ./wearit-frontend
    container_name: wearit_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./wearit-frontend:/app
      - ./app/node_modules
    depends_on:
      - backend
      
volumes:
  postgres_data: