version: "3.9"

services:
  # 1. Database Service (Ab yeh variables use karega)
  db:
    image: postgres:15
    container_name: wearit_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. FastAPI Backend Service
  backend:
    build: ./backend
    container_name: wearit_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env         # Yeh line EC2 par baithi .env se saari values auto-inject karegi
    volumes:
      - ./backend:/app

volumes:
  postgres_data: